/// Primary analytical fact table. Grain: one row per intake event, as recorded by ShelterBuddy.
/// One animal with two separate intakes produces two fact rows sharing one Animal Key.
/// Supports Foster Discovery reporting and Foster Placement Rate calculations. Date analysis is bound to Intake Date, not Foster Date.
table 'Animal Intakes'
	lineageTag: 5c48614a-f13f-4ef7-b79d-47f632d579c5

	/// Count of intake events. Not a distinct-animal count - see grain note above.
	measure 'Intake Count' = SUM('Animal Intakes'[IntakeCount])
		formatString: #,##0
		lineageTag: f60d2a94-d13e-4093-b28c-3fd02337e155

	/// Count of intake events where the animal experienced at least one foster placement.
	measure 'Animals Ever Fostered' = SUM('Animal Intakes'[FosterFlag])
		formatString: #,##0
		lineageTag: a9ef8d00-30f8-468e-a4fb-4e6fecb22436

	/// Percentage of intake events that experienced foster placement. Recalculates under any filter context.
	measure 'Foster Placement Rate (%)' = DIVIDE([Animals Ever Fostered], [Intake Count])
		formatString: 0.00%
		lineageTag: 4828a3b4-eff3-4ac6-b8a1-06377b96ad63

	/// ShelterBuddy's unique intake transaction ID (natural key). Guarantees grain uniqueness at load; backend/QA reconciliation only.
	/// NOTE: hidden base columns below (IntakeCount, FosterFlag) use their unspaced technical names, not spaced
	/// business names, specifically to avoid colliding with the measures above ('Intake Count', via 'Animals Ever
	/// Fostered' -> 'Foster Flag'). Per modeling-guidelines.md: a measure and its aggregated base column must not
	/// share the same name. These columns are hidden and never shown to report authors.
	column 'Source Intake ID'
		dataType: string
		isHidden
		lineageTag: 05b43c12-dd09-4763-b02c-2792a5ac74cb
		sourceColumn: SourceIntakeID

	column 'Date Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3fa1568d-b2fb-4cee-9c06-70e32a34051a
		summarizeBy: none
		sourceColumn: DateKey

	column 'Centre ID'
		dataType: string
		isHidden
		lineageTag: 85e4f87c-f13b-4139-918f-ad8b83c69139
		sourceColumn: CentreID

	column 'Intake Type ID'
		dataType: string
		isHidden
		lineageTag: 23e11205-d16e-43c0-94cf-f1a5043229f0
		sourceColumn: IntakeTypeID

	column 'Animal Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e3831d74-0fb6-47fb-8d1e-1eda58bbd74b
		summarizeBy: none
		sourceColumn: AnimalKey

	/// Constant value = 1. Base column for the Intake Count measure - hidden; use the measure instead.
	column IntakeCount
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 62b9cf7c-9ab0-4fd1-8d78-f55b8f43d7c7
		sourceColumn: IntakeCount

	/// Integer 0/1, not Boolean, so it can be SUM()'d directly. Base column for the Animals Ever Fostered measure - hidden; use the measure instead.
	column FosterFlag
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4b475970-8e82-4fa8-9c60-71ef03bc72b0
		sourceColumn: FosterFlag

	partition 'Animal Intakes' = m
		mode: import
		source =
				let
					// Load the Animal Intakes fact fixture from the local Prototype-mode data folder.
					Source = Csv.Document(File.Contents(#"DataFolder" & "Fact_AnimalIntake.csv"), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
					#"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed column types" = Table.TransformColumnTypes(#"Promoted headers", {
						{"SourceIntakeID", type text}, {"DateKey", Int64.Type}, {"CentreID", type text},
						{"IntakeTypeID", type text}, {"AnimalKey", Int64.Type}, {"IntakeCount", Int64.Type}, {"FosterFlag", Int64.Type}
					})
				in
					#"Changed column types"

	annotation PBI_ResultType = Table

