/// Calendar date dimension. One row per calendar day, contiguous, 2024-01-01 through 2025-12-31.
/// Built upstream in Microsoft Fabric per RDLC OS model-first design decision (governed table, not DAX-generated).
table Date
	lineageTag: cd7f3806-4bc7-4cc0-aa47-b6942b446000
	dataCategory: Time

	column 'Date Key'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: c2d45025-739d-4772-9f47-b1a29520d3b0
		summarizeBy: none
		sourceColumn: DateKey

	/// Calendar date. Use this column, not Date Key, for all report visuals and slicers.
	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3bf131c4-9698-4332-9724-67c619244c8e
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	/// Calendar year of the intake date.
	column Year
		dataType: int64
		formatString: 0
		lineageTag: 0b0157d1-54d8-4024-9ad1-f6a77b72861b
		summarizeBy: none
		sourceColumn: Year

	/// Calendar quarter (Q1-Q4) of the intake date.
	column Quarter
		dataType: string
		lineageTag: 53c10bd6-6dd6-47f0-9505-8c6472b96651
		sourceColumn: Quarter

	column Month
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 62474fa1-089a-4e76-b18d-6cd92be0b602
		summarizeBy: none
		sourceColumn: Month

	/// Month name, sorted by the numeric Month column (not alphabetically).
	column 'Month Name'
		dataType: string
		lineageTag: 43c60a0f-c856-4e26-8a7f-3e54e64a5b34
		sourceColumn: MonthName
		sortByColumn: Month

	/// ISO week label for the intake date (e.g., W22).
	column Week
		dataType: string
		lineageTag: 99ff80ca-fb36-4a10-84e3-f8d609539ba5
		sourceColumn: Week

	/// Winter (Dec-Feb) / Spring (Mar-May) / Summer (Jun-Aug) / Fall (Sep-Nov). Supports BC seasonal / "kitten season" analysis.
	column Season
		dataType: string
		lineageTag: 59f6db11-e994-4e20-8da7-5e9aaa4de269
		sourceColumn: Season

	hierarchy 'Calendar Hierarchy'
		lineageTag: 68a9dc25-3ebe-454a-b054-e6ba7165938a

		level Year
			lineageTag: 1c5769c6-69fe-42ae-9c02-20a9332f9347
			column: Year

		level Quarter
			lineageTag: 241cebf8-93ce-48ab-a699-1c3a4a04a98b
			column: Quarter

		level 'Month Name'
			lineageTag: 48ef977d-1548-4bb4-afa3-c73fbc0696d4
			column: 'Month Name'

		level Date
			lineageTag: 1f0fd103-229d-4c46-bf29-27ea356203f6
			column: Date

	partition Date = m
		mode: import
		source =
				let
					// Load the Date dimension fixture from the local Prototype-mode data folder.
					Source = Csv.Document(File.Contents(#"DataFolder" & "Dim_Date.csv"), [Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
					#"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed column types" = Table.TransformColumnTypes(#"Promoted headers", {
						{"DateKey", Int64.Type}, {"Date", type date}, {"Year", Int64.Type},
						{"Quarter", type text}, {"Month", Int64.Type}, {"MonthName", type text},
						{"Week", type text}, {"Season", type text}
					})
				in
					#"Changed column types"

	annotation PBI_ResultType = Table

