/// Animal dimension. SCD Type 1 (overwrite). Grain: one row per distinct animal (AnimalID from ShelterBuddy).
table Animal

	column 'Animal Key'
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: AnimalKey

	/// ShelterBuddy's natural Animal ID. Retained to support a future # Animals (distinct count) measure,
	/// since the fact table's grain is the intake event, not the animal - the same animal can have multiple intakes.
	column 'Animal ID'
		dataType: string
		isHidden
		sourceColumn: AnimalID

	/// Animal species as recorded in ShelterBuddy. Use Species Group for a higher-level, Data-Owner-governed rollup.
	column Species
		dataType: string
		sourceColumn: Species

	/// Data-Owner-confirmed rollup grouping for Species (e.g., Cat, Dog, Small Animal).
	/// Mapping is NOT yet complete - "Other" is a temporary placeholder for species not yet mapped by the Data Owner, not a finished category.
	column 'Species Group'
		dataType: string
		sourceColumn: SpeciesGroup

	/// Animal breed as recorded in ShelterBuddy.
	column Breed
		dataType: string
		sourceColumn: Breed

	/// Neonate / Juvenile / Adult / Senior - native ShelterBuddy field, no derivation required.
	column 'Age Group'
		dataType: string
		sourceColumn: AgeGroup

	/// Retained as a low-cost, plausible driver. Likely correlated with Species x Age Group (Neonate), not independent - treat findings as a hypothesis.
	column Sex
		dataType: string
		sourceColumn: Sex

	partition Animal = m
		mode: import
		source =
			let
				// Load the Animal dimension fixture from the local Prototype-mode data folder.
				Source = Csv.Document(File.Contents(#"DataFolder" & "Dim_Animal.csv"), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed column types" = Table.TransformColumnTypes(#"Promoted headers", {
					{"AnimalKey", Int64.Type}, {"AnimalID", type text}, {"Species", type text},
					{"SpeciesGroup", type text}, {"Breed", type text}, {"AgeGroup", type text}, {"Sex", type text}
				})
			in
				#"Changed column types"

	annotation PBI_ResultType = Table
