/// Intake Type dimension. Grain: one row per ShelterBuddy intake type (34 source values). SCD Type 1 (overwrite).
table 'Intake Type'

	column 'Intake Type ID'
		dataType: string
		isHidden
		sourceColumn: IntakeTypeID

	/// Raw ShelterBuddy intake type (e.g., Stray, Owner Surrender, Returns) - 34 distinct values. Use Intake Group for the governed 8-group rollup.
	column 'Intake Type'
		dataType: string
		sourceColumn: IntakeType

	/// Data-Owner-governed rollup grouping (8 groups). Many-to-one from Intake Type. List may evolve.
	column 'Intake Group'
		dataType: string
		sourceColumn: IntakeGroup

	partition 'Intake Type' = m
		mode: import
		source =
			let
				// Load the Intake Type dimension fixture from the local Prototype-mode data folder.
				Source = Csv.Document(File.Contents(#"DataFolder" & "Dim_Intake.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed column types" = Table.TransformColumnTypes(#"Promoted headers", {
					{"IntakeTypeID", type text}, {"IntakeType", type text}, {"IntakeGroup", type text}
				})
			in
				#"Changed column types"

	annotation PBI_ResultType = Table
